const { NOTIFICATION_TYPES, NOTIFICATION_PRIORITIES } = require('../enums/notificationEnums');

const NOTIFICATION_TYPE_LABELS = Object.freeze({
  [NOTIFICATION_TYPES.WELCOME]: 'Welcome Email',
  [NOTIFICATION_TYPES.EMAIL_VERIFICATION]: 'Email Verification',
  [NOTIFICATION_TYPES.EMAIL_VERIFIED]: 'Email Verification Confirmed',
  [NOTIFICATION_TYPES.PHONE_VERIFICATION]: 'Phone Verification',
  [NOTIFICATION_TYPES.PHONE_VERIFIED]: 'Phone Verification Confirmed',
  [NOTIFICATION_TYPES.FACIAL_VERIFICATION]: 'Facial Verification',
  [NOTIFICATION_TYPES.FACIAL_VERIFIED]: 'Facial Verification Confirmed',
  [NOTIFICATION_TYPES.PASSWORD_RESET]: 'Password Reset',
  [NOTIFICATION_TYPES.PASSWORD_CHANGED]: 'Password Changed',
  [NOTIFICATION_TYPES.PROFILE_UPDATED]: 'Profile Updated',
  [NOTIFICATION_TYPES.LISTING_CREATED]: 'Listing Created',
  [NOTIFICATION_TYPES.LISTING_APPROVED]: 'Listing Approved',
  [NOTIFICATION_TYPES.LISTING_REJECTED]: 'Listing Rejected',
  [NOTIFICATION_TYPES.MESSAGE_RECEIVED]: 'New Message',
  [NOTIFICATION_TYPES.ACCOUNT_SUSPENDED]: 'Account Suspended',
  [NOTIFICATION_TYPES.ACCOUNT_REACTIVATED]: 'Account Reactivated',
  [NOTIFICATION_TYPES.SECURITY_ALERT]: 'Security Alert',
  [NOTIFICATION_TYPES.SYSTEM_MAINTENANCE]: 'System Maintenance',
  [NOTIFICATION_TYPES.PROMOTION]: 'Promotion',
  [NOTIFICATION_TYPES.AUCTION_ACCESS]: 'Auction Access',
  [NOTIFICATION_TYPES.PAYMENT_CONFIRMATION]: 'Payment Confirmation',
  [NOTIFICATION_TYPES.BOOST_EXPIRY_WARNING_5D]: 'Boost Expiry Warning (5 Days)',
  [NOTIFICATION_TYPES.BOOST_EXPIRY_WARNING_3D]: 'Boost Expiry Warning (3 Days)',
  [NOTIFICATION_TYPES.BOOST_EXPIRY_WARNING_24H]: 'Boost Expiry Warning (24 Hours)',
  [NOTIFICATION_TYPES.BOOST_EXPIRY_WARNING_6H]: 'Boost Expiry Warning (6 Hours)',
  [NOTIFICATION_TYPES.BOOST_EXPIRED]: 'Boost Expired',
  [NOTIFICATION_TYPES.SUBSCRIPTION]: 'Subscription'
});

const NOTIFICATION_PRIORITY_LABELS = Object.freeze({
  [NOTIFICATION_PRIORITIES.LOW]: 'Low',
  [NOTIFICATION_PRIORITIES.NORMAL]: 'Normal',
  [NOTIFICATION_PRIORITIES.HIGH]: 'High',
  [NOTIFICATION_PRIORITIES.URGENT]: 'Urgent'
});

module.exports = {
  NOTIFICATION_TYPE_LABELS,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_PRIORITY_LABELS
};
